keypoint_names: ['Nose', 'Neck', 'RShoulder', 'RElbow', 'RWrist', 'LShoulder', 'LElbow', 'LWrist', 'RHip', 'RKnee', 'RAnkle', 'LHip', 'LKnee', 'LAnkle', 'REye', 'LEye', 'REar', 'LEar']
new_fixed_width: 1000
bisection:
  correction_angle: 15
  cone_opening_angle: 30
  cone_shape_length: 450
  left_pose_points: [0,1,8]
  right_pose_points: [0,1,11]
pose_abstraction:
  keypoint_list:
    top: [0,1,14,15,16,17]
    right: [10,9,8]
    left: [13,12,11]
keypoint_colors:
  - [0,120,40]
  - [105,160,50]
  - [102,211,255]
  - [255,120,0]
  - [30,30,170]
  - [50,130,60]
  - [80,10,130]
  - [60,0,140]
  - [100,200,100]
  - [102,211,255]
  - [100,100,200]
  - [40,120,0]
  - [20,100,200]
  - [50,130,60]
  - [100,20,200]
  - [60,0,140]
  - [0,200,255]
  - [100,255,100]
  - [0,255,100]
  - [100,200,230]
  - [200,0,230]
  - [255,60,50]
  - [255,160,150]